name: Guardian - Workflow Scanner
description: "Static analysis of workflows"

inputs:
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Guardian analysis
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_EVENT_NAME: ${{ env.GITHUB_EVENT_NAME }}
        GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
        GITHUB_REF: ${{ env.GITHUB_REF }}
      run: |
        python analysis/main.py
