name: Guardian Check

on:
  pull_request:
  push:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  guardian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install PyGithub pyyaml
      - name: Run Guardian
        shell: bash
        env:
            GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
            GITHUB_EVENT_NAME: ${{ github.event_name }}
            GITHUB_EVENT_PATH: ${{ github.event_path }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_SHA: ${{ github.sha }}
            GITHUB_REF: ${{ github.ref }}
        run: |
          python analysis/main.py
