name: Guardian - Workflow Scanner
description: "Static analysis of workflows"
inputs:
  github_token:
    description: 'Github token defaults to GITHUB_TOKEN secret'
    required: false
runs:
  using: "composite"
  steps:
  - name: Checkout repo
    uses: actions/checkout@v4
  
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    
  - name: Run Guardian analysis
    shell: bash
    env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
    run: |
      python analysis/main.py